local set = vim.opt
local let = vim.g

set.number = true
set.ruler = true
set.mouse = 'a'
set.clipboard = 'unnamedplus'
set.ignorecase = true
set.smartcase = true
set.ignorecase = true
set.tabstop = 4
set.shiftwidth = 4
set.expandtab = true
set.cursorline = true
set.foldmethod = 'indent'
set.foldlevel = 99
set.scrolloff = 8
-- let.colorscheme = 'gruvbox'
-- set.termguicolors = false
-- set.background = 'dark'
