require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.cmp"
require "user.lsp"
require "user.treesitter"
require "user.telescope"
-- require "user.nvim-tree"
require "user.gitsigns"
require "user.colorscheme"
require "user.lualine"
require "user.toggleterm"
require "user.comment"
require "user.autopairs"
require "user.mini"
